

export const rows = [
  {
    id: 1,
    name: "Jon Snow",
    email: "jonsnow@gmail.com",
    age: 35,    
    status : 0,
    requests: "View Log",
    resources: "Assigned",
    access: "Manage",
  },
  {
    id: 2,
    name: "Cersei Lannister",
    email: "cerseilannister@gmail.com",
    age: 42,    
    status : 0,
    requests: "View Log",
    resources: "Assigned",
    access: "Manage",
  },
  {
    id: 3,
    name: "Jaime Lannister",
    email: "jaimelannister@gmail.com",
    age: 45,    
    status : 1,
    requests: "View Log",
    resources: "Assigned",
    access: "Manage",
  },
  {
    id: 4,
    name: "Anya Stark",
    email: "anyastark@gmail.com",
    age: 16,    
    status : 0,
    requests: "View Log",
    resources: "Assigned",
    access: "Manage",
  },
  {
    id: 5,
    name: "Daenerys Targaryen",
    email: "daenerystargaryen@gmail.com",
    age: 31,    
    status : 1,
    requests: "View Log",
    resources: "Assigned",
    access: "Manage",
  },
  {
    id: 6,
    name: "Ever Melisandre",
    email: "evermelisandre@gmail.com",
    age: 150,   
    status : 1,
    requests: "View Log",
    resources: "Assigned",
    access: "Manage",
  },
  {
    id: 7,
    name: "Ferrara Clifford",
    email: "ferraraclifford@gmail.com",
    age: 44,    
    status : 0,
    requests: "View Log",
    resources: "Assigned",
    access: "Manage",
  },
  {
    id: 8,
    name: "Rossini Frances",
    email: "rossinifrances@gmail.com",
    age: 36,    
    status : 0,
    requests: "View Log",
    resources: "Assigned",
    access: "Manage",
  },
  {
    id: 9,
    name: "Harvey Roxie",
    email: "harveyroxie@gmail.com",
    age: 65,    
    status : 0,
    requests: "View Log",
    resources: "Assigned",
    access: "Manage",
  },
];

